/**
 * const prefixCls = 'style-935517';
 * const images = '/static/images/src/event/car/Post';
 * @Author: czy0729
 * @Date: 2018-11-08 14:29:32
 * @Last Modified by: czy0729
 * @Last Modified time: 2018-11-23 10:15:34
 * @Path bt_mb_new /src/event/car/Post/ds.js.git
 */
import Utils from '@utils';

export const images = Utils.cdn('/static/images/src/event/car/Post');
export const infoTypeDS = {
  video: 1,
  image: 2,
  article: 3
};
export const mainGoodsDS = [
  { label: '神鹤轻强硬', value: 208 },
  { label: '天弧斩月刀-鲤（黑蓝尊贵版）', value: 976 },
  { label: '天弧斩月刀-鲤（黑银轻赢版）', value: 958 },
  { label: '神鹤战斗极', value: 792 },
  { label: '金迦潘求败', value: 211 },
  { label: '天弧斩月刀-鲤（黑白精英版）', value: 923 },
  { label: '天弧斩月刀-鲤（黑金进取版）', value: 922 },
  { label: '金迦潘引领', value: 212 },
  { label: '金迦潘硬弓', value: 210 },
  { label: '金迦潘强弓', value: 209 },
  { label: '桃园财神终极版', value: 215 },
  { label: '彪悍黑坑技5H6H7H', value: 803 },
  { label: '神乐暴强硬', value: 237 },
  { label: '棍王硬攻强攻', value: 374 },
  { label: '财神超硬调', value: 219 },
  { label: '大显神通普惠版', value: 575 },
  { label: '大显神通超硬', value: 239 },
  { label: '大显神通鲫硬版', value: 241 },
  { label: '潇裟狂强弩', value: 257 },
  { label: '傲江雪手作', value: 1062 },
  { label: '老首长系列长竿', value: 382 },
  { label: '爆草所长版', value: 371 },
  { label: '洪发山巨物', value: 364 },
  { label: '财神超硬调纪念版', value: 362 },
  { label: '千鹤超硬调', value: 359 },
  { label: '红花金棍吴郭版', value: 357 },
  { label: '神武鲤硬调', value: 351 },
  { label: '恶棍', value: 327 },
  { label: '恶霸之暴强', value: 325 },
  { label: '红环黑棍【战斗】', value: 324 },
  { label: '鬼斧神工', value: 322 },
  { label: '洪发山鲤硬调纪念版', value: 310 },
  { label: '刚厉特作大物', value: 307 },
  { label: '大黑脘', value: 300 },
  { label: '洪发山强弓', value: 299 },
  { label: '洪发山硬作', value: 298 },
  { label: '洪发山大物', value: 297 },
  { label: '福山', value: 296 },
  { label: '洪发山硬弓', value: 295 },
  { label: '有乐町劲功', value: 294 },
  { label: '胜北浪强弓', value: 293 },
  { label: '傲江雪特作', value: 292 },
  { label: '神武巨物鲤', value: 291 },
  { label: '大武生鲤', value: 290 },
  { label: '财神之神乐', value: 268 },
  { label: '财神黄金八万', value: 267 },
  { label: '弩火天尊（硬）', value: 266 },
  { label: '火舞', value: 265 },
  { label: '彪悍特作大物', value: 264 },
  { label: '宫本武藏鲤', value: 263 },
  { label: '刚厉特作', value: 262 },
  { label: '柴舟', value: 261 },
  { label: '神鹤巨物鲤', value: 260 },
  { label: '红缨枪鲤硬调', value: 259 },
  { label: '爆草青鲟版', value: 258 },
  { label: '财神鲤硬调', value: 256 },
  { label: '财神鲤硬调五周年', value: 255 },
  { label: '魔裟斗强弓', value: 254 },
  { label: '咏春轻细硬', value: 253 },
  { label: '弩火天尊战斗', value: 252 },
  { label: '如来终极版', value: 251 },
  { label: '大门裸棍轻量版', value: 250 },
  { label: '代官山', value: 249 },
  { label: '大门裸棍常规版', value: 248 },
  { label: '洪发山轻细硬', value: 247 },
  { label: '咏春并继', value: 246 },
  { label: '炎之鲫硬调', value: 245 },
  { label: '贺春鲫硬调', value: 244 },
  { label: '财神轻细硬', value: 243 },
  { label: '东势鲫硬调', value: 242 },
  { label: '恶棍-欺硬怕软', value: 240 },
  { label: '爆草加强版', value: 238 },
  { label: '爆草定制版', value: 236 },
  { label: '魔裟斗综合金版花纹', value: 235 },
  { label: '财神竞技', value: 234 },
  { label: '神乎其技', value: 233 },
  { label: '彪悍', value: 232 },
  { label: '财神吴郭版', value: 231 },
  { label: '大门羽川丽', value: 230 },
  { label: '宗师经典硬作', value: 229 },
  { label: '宗师', value: 228 },
  { label: '池霸竞技吴郭版7H', value: 226 },
  { label: '池霸竞技仁', value: 224 },
  { label: '神棍超硬调', value: 223 },
  { label: '竞鲫本汀钓鱼学院纪念版', value: 222 },
  { label: '竞鲫超硬调', value: 221 },
  { label: '傲江雪并继鲤调子', value: 220 },
  { label: '汀神青鲟轻硬大物', value: 218 },
  { label: '汀神限量版', value: 217 },
  { label: '汀神轻硬大物', value: 216 },
  { label: '宫本武藏大师版', value: 214 },
  { label: '银棍', value: 213 }
];
